[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "sendery-django"
version = "0.1.2"
description = "Sendery template email client for Django"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
dependencies = ["sendery>=0.1.2,<0.2", "Django>=5.2,<5.3"]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Documentation = "https://sendery.co/en/docs/django"
Repository = "https://github.com/sendery-co/sendery-django"
